.goreleaser.yml, internal/client/client.go, main.go, version/version.go
changed to request User-Agent depending on provider version.
notice: it's have to build with ldflags. if it's empty, version does not added to user-agent.
```
go build -ldflags="-s -w -X \"terraform-provider-trocco/version.ProviderVersion=x\"" -o terraform-provider-trocco 
```
=> add fixed user-agent

docs/resources/team.md, internal/client/client.go, internal/provider/team_resource.go, internal/provider/validator/at_least_one_team_admin_validator.go
This pull request includes changes to the error handling in the `internal/client/client.go` file to provide more detailed error messages. The most important changes include the addition of a new field to the `ErrorOutput` struct and modifications to the error handling logic in the `do` function.
Enhancements to error handling:
* [`internal/client/client.go`](diffhunk://#diff-3b1f8149deb45d304c69c856bcd1b9b628961fb6000486cb39172a99cb8de514L70-R71): Added a `Message` field to the `ErrorOutput` struct to handle 400 bad request errors.
* [`internal/client/client.go`](diffhunk://#diff-3b1f8149deb45d304c69c856bcd1b9b628961fb6000486cb39172a99cb8de514R109-R116): Updated the `do` function to check for the new `Message` field and return appropriate error messages based on the presence of `Error` or …
=> Handling of error messages for 4xx error mesesage and team members were not required to be in order.

docs/resources/connection.md, examples/resources/trocco_connection/bigquery.tf, examples/resources/trocco_connection/gcs.tf, internal/client/connection.go, internal/provider/connection_resource.go, internal/provider/types.go
It adds a new connector type `gcs`.
- TROCCO's Web API for GCS is not yet publicly available, so do not merge right now.
- Add connector_type: gcs
- Add parameters for ConnectionsInput: application_name, service_account_email
=> add connection_type: gcs

docs/resources/job_definition.md, internal/provider/job_definition_resource.go, internal/provider/models/job_definitions/filter/filter_column.go, internal/provider/planmodifier/filter_column_plan_modifier.go, internal/provider/schema/job_definition/bigquery_output_option.go, internal/provider/schema/job_definition/filters/filter_columns.go, internal/provider/schema/job_definition/filters/filter_string_transforms.go, internal/provider/schema/job_definition/gcs_input_option.go, internal/provider/schema/job_definition/mysql_input_option.go, internal/provider/schema/job_definition/parser/csv_parser.go, internal/provider/schema/job_definition/parser/excel_parser.go, internal/provider/schema/job_definition/parser/jsonl_parser.go, internal/provider/schema/job_definition/parser/jsonpath_parser.go, internal/provider/schema/job_definition/parser/ltsv_parser.go
This pull request includes several changes to the schema definitions for various job definition resources in the internal provider. The main focus is on making attributes optional and computed, and setting default values for them using the `booldefault`, `int64default`, and `stringdefault` packages.
* `internal/provider/job_definition_resource.go`:
- Changed `is_runnable_concurrently` and `retry_limit` attributes to be optional and computed, with default values set.
* `internal/provider/schema/job_definition/bigquery_output_option.go`:
- Updated attributes such as `mode`, `auto_create_dataset`, `auto_create_table`, `open_timeout_sec`, `timeout_sec`, `send_timeout_sec`, `read_timeout_sec`, `retries`, and `location` to be optional and computed, with default values set. …
=> add default values

internal/provider/connection_resource.go
Originally, I wanted to error when a required parameter was not set, 
but the implementation actually generated an error for `unknown` types.
- use IsNull()
=> fix: use IsNull

internal/client/connection.go
- remove unused params from connector type: `mysql`
Sensitive parameters (like SSLCA, or GatewayPassword) that were originally implemented,
are not included from server response and not used elsewhere in terraform provider.
(only client sends these by POST/PATCH and saved in tfstate)
So this PR is removing unused parameters from code.
- remove unused params
=> remove unused params for HTTP response

docs/resources/connection.md, examples/resources/trocco_connection/postgresql.tf, internal/client/connection.go, internal/provider/connection_resource.go, templates/resources/connection.md.tmpl
- It adds a new connector type `postgresql`.
- TROCCO's Web API for PostgreSQL is not yet publicly available, so do not merge right now.
- Add connector_type: postgresql
=> add connection_type: PostgreSQL

.golangci.yml
This pull request includes a minor change to the `.golangci.yml` configuration file. The change corrects the `max-per-linter` setting to `max-issues-per-linter` to align with the correct configuration key.
Configuration change:
* [`.golangci.yml`](diffhunk://#diff-6179837f7df53a6f05c522b6b7bb566d484d5465d9894fb04910dd08bb40dcc9L4-R4): Corrected the configuration key from `max-per-linter` to `max-issues-per-linter`.
Ref:
- https://github.com/golangci/golangci-lint-action/pull/1171
- https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
=> fix typo property name

docs/resources/job_definition.md, examples/resources/trocco_job_definition/filter_column.tf
This pull request includes changes to the `trocco_job_definition` resource in both the documentation and example files. The primary change is the removal of the `json_expand_columns` attribute from various column definitions.
Changes in documentation:
* [`docs/resources/job_definition.md`](diffhunk://#diff-9d7b77f8e2e77493de0159fbca3ba3eaeddf1a2855b0348afc710325eeb90cc8L254): Removed the `json_expand_columns` attribute from the `id`, `name`, and `timestamp` column definitions. [[1]](diffhunk://#diff-9d7b77f8e2e77493de0159fbca3ba3eaeddf1a2855b0348afc710325eeb90cc8L254) [[2]](diffhunk://#diff-9d7b77f8e2e77493de0159fbca3ba3eaeddf1a2855b0348afc710325eeb90cc8L263) [[3]](diffhunk://#diff-9d7b77f8e2e77493de0159fbca3ba3eaeddf1a2855b0348afc710325eeb90cc8L272)
Changes in example files:
* …
=> Update documentation for filter_columns

docs/resources/job_definition.md, examples/resources/trocco_job_definition/gcs_to_bigquery.tf, examples/resources/trocco_job_definition/mysql_to_bigquery.tf, examples/resources/trocco_job_definition/output_options/bigquery_output_option.tf, internal/client/entity/job_definition/output_option/bigquery.go, internal/client/parameter/job_definition/output_option/bigquery.go, internal/provider/job_definition_resource_test.go, internal/provider/model/job_definition/output_option/bigquery.go, internal/provider/schema/job_definition/bigquery_output_option.go
The auto_create_table option has been removed as it is a meaningless flag even if specified.
=> remove auto_create_table option in output_bigquery option

docs/resources/job_definition.md, examples/resources/trocco_job_definition/input_options/salesforce_input_option.tf, examples/resources/trocco_job_definition/output_options/salesforce_output_option.tf, internal/client/entity/job_definition/input_option/salesforce.go, internal/client/entity/job_definition/output_option/salesforce.go, internal/client/job_definition.go, internal/client/parameter/job_definition/input_option/salesforce.go, internal/client/parameter/job_definition/output_option/salesforce.go, internal/provider/model/job_definition/input_option.go, internal/provider/model/job_definition/input_option/salesforce.go, internal/provider/model/job_definition/output_option.go, internal/provider/model/job_definition/output_option/salesforce.go, internal/provider/planmodifier/salesforce_input_option_plan_modifier.go, internal/provider/planmodifier/salesforce_output_option_plan_modifier.go, internal/provider/schema/job_definition/input_option.go, internal/provider/schema/job_definition/output_option.go, internal/provider/schema/job_definition/salesforce_input_option.go, internal/provider/schema/job_definition/salesforce_output_option.go, templates/resources/job_definition.md.tmpl
This pull request introduces support for Salesforce input and output options in the job definition schema and related files. The changes include updates to documentation, new structs for Salesforce options, and modifications to existing structs to integrate the new options.
* Added `salesforce_input_option` and `salesforce_output_option` attributes to the job definition documentation in `docs/resources/job_definition.md`. [[1]](diffhunk://#diff-9d7b77f8e2e77493de0159fbca3ba3eaeddf1a2855b0348afc710325eeb90cc8R1023) [[2]](diffhunk://#diff-9d7b77f8e2e77493de0159fbca3ba3eaeddf1a2855b0348afc710325eeb90cc8R1326-R1375) [[3]](diffhunk://#diff-9d7b77f8e2e77493de0159fbca3ba3eaeddf1a2855b0348afc710325eeb90cc8R1430) [[4]](diffhunk://#diff-9d7b77f8e2e77493de0159fbca3ba3eaeddf1a2855b0348afc710325eeb90cc …
=> support salesforce input and output option

docs/resources/label.md, examples/resources/trocco_label/resource.tf
#FFFFFF background is not a good color for a label, so changing example to #FF0000.
=> Sample label color changed to better value

internal/provider/bigquery_datamart_definition_resource.go
This PR fixes the problem that cannot set labels to datamart definitions.
=> fix: revert datamart label change

GNUmakefile, docs/resources/connection.md, internal/client/connection.go, internal/provider/connection_resource.go, internal/provider/connection_resource_test.go
This pull request includes changes to the `connection` resource to support additional database drivers and improve the handling of the `driver` field. The most important changes include updating the documentation, modifying the `CreateConnectionInput` and `UpdateConnectionInput` structs, and enhancing the schema for the `driver` field.
Support for additional database drivers:
* [`docs/resources/connection.md`](diffhunk://#diff-e00ef64002ad48ae9291de0a2b9fc0147d3820891da4a7ce049c5a705b107600L201-R205): Updated the `driver` field description to include support for Snowflake and MySQL drivers, in addition to PostgreSQL. Added possible values for each database type.
Handling of the `driver` field:
* [`internal/client/connection.go`](diffhunk://#diff-e1410d53fccb7a6e5598f02d41e1b9e8e3a9d7a522ad …
=> add driver for snowflake/mysql

internal/provider/job_definition_resource.go, internal/provider/job_definition_resource_test.go, internal/provider/model/job_definition/label.go
It fixes the problem on importing job definitions with labels.
FYI: https://github.com/trocco-io/terraform-provider-trocco/pull/68
--
This pull request includes changes to the `internal/provider/job_definition_resource.go` and introduces a new file `internal/provider/model/job_definition/label.go` to refactor and improve the handling of labels in job definitions. The most important changes include updating the `Labels` field to use the new `Label` type and modifying the related methods to use the new `NewLabels` function.
Refactoring and improvements:
* [`internal/provider/job_definition_resource.go`](diffhunk://#diff-bc5561d888ce74cb3694ee241401f9f5af26e7b9ff992036f6619e3c3e063c9dL201-R201): Changed the `Labels` field in the `jobDefinitionResourceModel` struct to use the new …
=> fix: Fix problem on importing job definitions

docs/resources/connection.md, examples/resources/trocco_connection/google_analytics4.tf, internal/provider/connection_resource.go, internal/provider/connection_resource_test.go, templates/resources/connection.md.tmpl
It adds a new connector type google_analytics4.
TROCCO's Web API for google_analytics4 is not yet publicly available, so do not merge right now.
Add connector_type: google_analytics4
=> add connection_type: google_analytics4

internal/provider/bigquery_datamart_definition_resource.go
- Changed the type of `custom_variable_settings` to `types.List`
- When `Create` or `Update`, convert to `[]customVariableSettingModel` using `ElementsAs` and pass it to the API
- Modified to convert API response (slice) to `types.List` so that it can be handled internally.
=> change custom_variable_settings type

docs/resources/job_definition.md, examples/resources/trocco_job_definition/input_options/kintone_input_option.tf, examples/testdata/job_definition/kintone_to_snowflake/create.tf, examples/testdata/job_definition/kintone_to_snowflake/update_app_id_required.tf, internal/client/entity/job_definition/input_option/kintone.go, internal/client/job_definition.go, internal/client/parameter/job_definition/input_option/kintone.go, internal/provider/job_definition_resource_test.go, internal/provider/model/job_definition/input_option.go, internal/provider/model/job_definition/input_option/kintone.go, internal/provider/planmodifier/kintone_input_option_column_plan_modifier.go, internal/provider/planmodifier/kintone_input_option_plan_modifier.go, internal/provider/schema/job_definition/input_option.go, internal/provider/schema/job_definition/kintone_input_option.go, templates/resources/job_definition.md.tmpl
This pull request is supported for Kintone as input option in resource trocco_job_definition.
<details>
<summary>example</summary>
```terraform
resource "trocco_job_definition" "from_kintone" {
name                     = "example_kintone_to_bigquery"
description              = "this is an example job definition for transferring data from kintone to bigquery"
is_runnable_concurrently = false
retry_limit              = 0
filter_columns = [
{
default                      = null
json_expand_columns          = null
json_expand_enabled          = false
json_expand_keep_base_column = false
name                         = "id"
src                          = "id"
type                         = "long"
},
]
input_option_type = "kintone"
input_option = {
kintone_input_option = {
kintone_connection_id …
```
=> support kintone input option

.github/workflows/pinact.yaml, .github/workflows/test.yml
- To mitigate supply chain attacks targeting GitHub Actions, perform pinning using the SHA by [pinact-action](https://github.com/suzuki-shunsuke/pinact-action).
- Confirmed that pinact is working in the following commit.
- https://github.com/trocco-io/terraform-provider-trocco/pull/97/commits/e0f98f42ae7c9cf7fe18ba617268ecb37e747869
=> Add pinact-action

docs/resources/connection.md, examples/resources/trocco_connection/import.tf
I previously added an import block example to the documentation in a different PR #78, but the import block for `connection` was incorrect.
This PR fixes that mistake.
=> docs: fix import block example

internal/provider/pipeline_definition_resource_test.go
This pull request adds an import test for the `trocco_pipeline_definition` resource.
If simply added, there would be a difference in the `trocco_pipeline_definition.tasks.0.key`.
```
=== RUN   TestAccPipelineDefinitionResourceWithImport
pipeline_definition_resource_test.go:63: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
map[string]string{
-       "tasks.0.key": "snowflake_data_check",
+       "tasks.0.key": "1",
}
```
Because key is not returned from TROCCO API,  so I used `ImportStateVerifyIgnore` to ignore it.
- ref https://github.com/hashicorp/terraform-provider-hashicups/blob/b82c725077386062e6260073dcd8a47e486f12d5/11-documentation-generation/internal/provider/order_resou …
=> add import state tests

internal/provider/bigquery_datamart_definition_resource.go, internal/provider/bigquery_datamart_definition_resource_test.go, internal/provider/testdata/bigquery_datamart_definition/create.tf
This pull request switches `trocco_bigquery_datamart_definition` `before_load` to a custom type.
**Details:**
- String value trimming with using `TrimmedStringValue `
- Update schema definitions
- Added related tests
=> update BeforeLoad field to use TrimmedStringValue custom type

internal/provider/model/pipeline_definition/pipeline_definition.go, internal/provider/pipeline_definition_resource.go, internal/provider/pipeline_definition_resource_test.go, internal/provider/testdata/pipeline_definition/bigquery_data_check/create.tf
This pull request switches `trocco_pipeline_definition` `description` to a custom type.
**Details:**
- String value trimming with using `TrimmedStringValue `
- Update schema definitions
- Added related tests
=> use TrimStringValue for description in pipeline_definition

internal/provider/bigquery_datamart_definition_resource.go, internal/provider/bigquery_datamart_definition_resource_test.go, internal/provider/testdata/bigquery_datamart_definition/truncate_with_before_load.tf, internal/provider/testdata/bigquery_datamart_definition/truncate_without_before_load.tf
This pull request introduces validation logic for the `write_disposition` field in BigQuery datamart definitions, ensuring compatibility with the `before_load` field, and adds corresponding test cases to verify this behavior. The changes enhance data integrity and prevent configuration errors.
**Details:**
- add validation
- add tests
=> Validate before load

internal/provider/schema/job_definition/parser/jsonl_parser.go
I fixed an issue where "json" was not accepted as a valid value for the type field in the columns attribute of jsonl_parser.
=> fix JsonlParserSchema

docs/resources/job_definition.md, internal/provider/schema/job_definition/google_spreadsheets_input_option.go, internal/provider/schema/job_definition/google_spreadsheets_output_option.go
Fixed incorrect connection type descriptions in the Google Spreadsheets input and output options documentation. The descriptions previously referred to "Snowflake connection" instead of "Google Spreadsheets connection".
- Fixed `google_spreadsheets_input_option.go`: Changed "Id of Snowflake connection" to "Id of Google Spreadsheets connection"
- Fixed `google_spreadsheets_output_option.go`: 
- Changed "Attributes of destination Snowflake settings" to "Attributes of destination Google Spreadsheets settings"
- Changed "Snowflake connection ID" to "Google Spreadsheets connection ID"
- Regenerated documentation using `tfplugindocs`
The documentation on the Terraform Registry contained misleading information that could confuse users. The Google Spreadsheets connection IDs were incorrectly …
=> fix google spreadsheets typo

.claude/commands/test-adhoc.md, .editorconfig, tests/adhoc/.gitignore
- Add Claude command for ad hoc testing with comprehensive instructions
- Update .editorconfig to include Makefile indentation rules
- Add .gitignore for tests/adhoc directory to exclude test artifacts
=> feat: add ad hoc testing infrastructure and configuration

internal/provider/schema/pipeline_definition/tasks.go
This PR fixes an issue where task_identifier values were duplicated when new tasks were added to the pipeline_definition resource. The update ensures that each task is assigned a unique task_identifier to prevent API errors during updates.
=> Fix duplicate task_identifier assignment when adding tasks to pipeline_definition
